steps:
  - name: alpine
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
    id: branch name
    entrypoint: sh
  - name: node
    args:
      - '-c'
      - |
        if [ -d "environments/$BRANCH_NAME/" ]; then
          chmod u+x build_tsconfigs.sh
          ./build_tsconfigs.sh
        fi
    id: build typescript
    entrypoint: bash
  - name: hashicorp/terraform
    args:
      - '-c'
      - |
        if [ -d "environments/pre_$BRANCH_NAME/" ]; then
          cd environments/pre_$BRANCH_NAME
          terraform init
        else
          for dir in environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFORM PRE INIT **************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform init || exit 1
            cd ../../
          done
        fi
    id: tf pre init
    entrypoint: sh
  - name: hashicorp/terraform
    args:
      - '-c'
      - |
        if [ -d "environments/pre_$BRANCH_NAME/" ]; then
          cd environments/pre_$BRANCH_NAME
          terraform plan
        else
          for dir in environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}  
            echo ""
            echo "*************** TERRAFOM PRE PLAN ***************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform plan || exit 1
            cd ../../
          done
        fi
    id: tf pre plan
    entrypoint: sh
  - name: hashicorp/terraform
    args:
      - '-c'
      - |
        if [ -d "environments/pre_$BRANCH_NAME/" ]; then
          cd environments/pre_$BRANCH_NAME      
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
          echo "*******************************************************************************"
        fi
    id: tf pre apply
    entrypoint: sh
  - name: hashicorp/terraform
    args:
      - '-c'
      - |
        if [ -d "environments/$BRANCH_NAME/" ]; then
          cd environments/$BRANCH_NAME
          terraform init
        else
          for dir in environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFORM INIT ******************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform init || exit 1
            cd ../../
          done
        fi
    id: tf init
    entrypoint: sh
  - name: hashicorp/terraform
    args:
      - '-c'
      - |
        if [ -d "environments/$BRANCH_NAME/" ]; then
          cd environments/$BRANCH_NAME
          terraform plan
        else
          for dir in environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}  
            echo ""
            echo "*************** TERRAFOM PLAN ******************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform plan || exit 1
            cd ../../
          done
        fi
    id: tf plan
    entrypoint: sh
  - name: hashicorp/terraform
    args:
      - '-c'
      - |
        if [ -d "environments/$BRANCH_NAME/" ]; then
          cd environments/$BRANCH_NAME      
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
          echo "*******************************************************************************"
        fi
    id: tf apply
    entrypoint: sh
